#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is used to produce materials for the following work:

# Doctoral Dissertation
# (c) by Manuel Schlund

# This work is licensed under a
# Creative Commons Attribution 4.0 International License.

# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by/4.0/>.

